#!/usr/bin/env python3
"""Add Referenced By sections to framework files."""

from pathlib import Path

def add_referenced_by_section(file_path):
    """Add Referenced By section to a framework file if it doesn't exist."""
    with open(file_path, 'r', encoding='utf-8') as f:
        content = f.read()

    # Check if it already has the section
    if '## Referenced By' in content:
        return False

    # Add the section at the end
    referenced_by_section = '''
---

## Referenced By

*This section is automatically generated by `make generate-backlinks`. Do not edit manually.*
'''

    # Append to end of file
    new_content = content.rstrip() + '\n' + referenced_by_section + '\n'

    with open(file_path, 'w', encoding='utf-8') as f:
        f.write(new_content)

    return True

def main():
    repo_root = Path(__file__).parent.parent.parent
    frameworks_dir = repo_root / 'docs' / 'frameworks'

    if not frameworks_dir.exists():
        print(f"Error: {frameworks_dir} does not exist")
        return

    modified_count = 0
    total_count = 0

    # Process all framework directories
    for framework_dir in ['soc2', 'gdpr', 'iso27001', 'iso27002', 'nist80053']:
        dir_path = frameworks_dir / framework_dir
        if not dir_path.exists():
            print(f"Warning: {dir_path} does not exist, skipping")
            continue

        for md_file in dir_path.glob('*.md'):
            if md_file.name == 'index.md':
                continue

            total_count += 1
            if add_referenced_by_section(md_file):
                modified_count += 1
                print(f"Added section to: {md_file.relative_to(repo_root)}")

    print(f"\nProcessed {total_count} files, modified {modified_count} files")

if __name__ == '__main__':
    main()
