#!/usr/bin/env python3
"""Clean all backlink sections, keeping only the header and note."""

import re
import glob

def clean_backlinks():
    patterns = [
        'custom/*.md',
        'standards/*.md',
        'processes/*.md',
        'policies/*.md',
        'charter/*.md',
        'soc2/*.md',
        'gdpr/*.md',
        'iso27001/*.md',
        'iso27002/*.md',
        'nist80053/*.md',
        'scf/*.md'
    ]

    files_cleaned = 0

    for pattern in patterns:
        for filepath in glob.glob(pattern):
            with open(filepath, 'r') as f:
                content = f.read()

            # Find the Referenced By section
            match = re.search(r'## Referenced By\n\n', content)
            if match:
                # Keep everything up to and including the header
                new_content = content[:match.end()]
                # Add the auto-gen note
                new_content += '*This section is automatically generated by `make generate-backlinks`. Do not edit manually.*\n\n'

                # Write back
                with open(filepath, 'w') as f:
                    f.write(new_content)

                files_cleaned += 1

    print(f"Cleaned backlinks from {files_cleaned} files")

if __name__ == '__main__':
    clean_backlinks()
