#!/usr/bin/env python3
"""
Migrate custom controls to controls directory structure.
Converts custom/*.md files to controls/{family}/{name}.md format
with proper IDs and formatting.
"""

import os
import re
from pathlib import Path

# Mapping of custom categories to control families
CATEGORY_TO_FAMILY = {
    "Access Control": "iam",
    "Data Protection": "data-management",
    "Endpoint Security": "endpoint-security",
    "Governance": "governance",
    "Infrastructure Security": "infrastructure-security",
    "Operational Security": "operational-security",
    "People Security": "personnel-security",
    "Vendor Management": "vendor-management",
}

def parse_frontmatter(content):
    """Extract frontmatter from markdown content."""
    match = re.match(r'^---\n(.*?)\n---\n(.*)$', content, re.DOTALL)
    if not match:
        return {}, content

    frontmatter_text = match.group(1)
    body = match.group(2)

    frontmatter = {}
    for line in frontmatter_text.split('\n'):
        if ':' in line:
            key, value = line.split(':', 1)
            frontmatter[key.strip()] = value.strip()

    return frontmatter, body

def slugify(text):
    """Convert text to lowercase slug."""
    text = text.lower()
    text = re.sub(r'[^a-z0-9]+', '-', text)
    text = text.strip('-')
    return text

def extract_sections(body):
    """Extract sections from markdown body."""
    sections = {}

    # Extract Objective
    obj_match = re.search(r'## Objective\n(.*?)(?=\n##|\Z)', body, re.DOTALL)
    if obj_match:
        sections['objective'] = obj_match.group(1).strip()

    # Extract Description
    desc_match = re.search(r'## Description\n(.*?)(?=\n##|\Z)', body, re.DOTALL)
    if desc_match:
        sections['description'] = desc_match.group(1).strip()

    # Extract Implementation Details
    impl_match = re.search(r'## Implementation Details\n(.*?)(?=\n##|\Z)', body, re.DOTALL)
    if impl_match:
        sections['implementation'] = impl_match.group(1).strip()

    # Extract Examples
    examples_match = re.search(r'## Examples\n(.*?)(?=\n##|\Z)', body, re.DOTALL)
    if examples_match:
        sections['examples'] = examples_match.group(1).strip()

    # Extract Audit Evidence
    evidence_match = re.search(r'## Audit Evidence\n(.*?)(?=\n##|\Z)', body, re.DOTALL)
    if evidence_match:
        sections['evidence'] = evidence_match.group(1).strip()

    # Extract Framework Mapping
    mapping_match = re.search(r'## Framework Mapping\n(.*?)(?=\n---|\Z)', body, re.DOTALL)
    if mapping_match:
        sections['framework_mapping'] = mapping_match.group(1).strip()

    return sections

def create_control_file(frontmatter, sections, family, control_id):
    """Generate new control file content."""
    title = frontmatter.get('title', '')
    slug = slugify(title)
    control_file_id = f"{family}-{slug}"

    # Build new frontmatter
    new_frontmatter = {
        'id': control_file_id,
        'type': 'control',
        'family': family,
        'title': title,
        'owner': frontmatter.get('owner', 'security-team'),
        'last_reviewed': frontmatter.get('last_reviewed', '2025-01-19'),
        'review_cadence': frontmatter.get('review_cadence', 'quarterly'),
    }

    # Build markdown content
    lines = []
    lines.append('---')
    for key, value in new_frontmatter.items():
        lines.append(f'{key}: {value}')
    lines.append('---')
    lines.append('')
    lines.append(f'# {title}')
    lines.append('')

    # Add objective
    lines.append('## Objective')
    lines.append('')
    lines.append(sections.get('objective', '[Control objective]'))
    lines.append('')

    # Add description if exists
    if 'description' in sections:
        lines.append('## Description')
        lines.append('')
        lines.append(sections['description'])
        lines.append('')

    # Add implementation
    lines.append('## Implementation')
    lines.append('')
    lines.append(sections.get('implementation', '[How this control is implemented]'))
    lines.append('')

    # Add examples if exists
    if 'examples' in sections:
        lines.append('## Examples')
        lines.append('')
        lines.append(sections['examples'])
        lines.append('')

    # Add evidence
    lines.append('## Evidence')
    lines.append('')
    lines.append(sections.get('evidence', '[Audit evidence for this control]'))
    lines.append('')
    lines.append('---')
    lines.append('')

    # Add framework mapping
    lines.append('## Framework Mapping')
    lines.append('')
    if 'framework_mapping' in sections:
        lines.append(sections['framework_mapping'])
    else:
        lines.append('<!-- Links to framework controls (SOC 2, GDPR, etc.) -->')
    lines.append('')
    lines.append('---')
    lines.append('')

    # Add Referenced By section
    lines.append('## Referenced By')
    lines.append('')
    lines.append('*This section is automatically generated by `make generate-backlinks`. Do not edit manually.*')
    lines.append('')

    return '\n'.join(lines), slug

def migrate_custom_controls():
    """Main migration function."""
    custom_dir = Path('../docs/custom')
    controls_dir = Path('../docs/controls')

    if not custom_dir.exists():
        print(f"Error: {custom_dir} does not exist")
        return

    migrated = []
    errors = []

    for custom_file in sorted(custom_dir.glob('*.md')):
        if custom_file.name == 'index.md':
            continue

        print(f"\nProcessing {custom_file.name}...")

        try:
            content = custom_file.read_text()
            frontmatter, body = parse_frontmatter(content)

            category = frontmatter.get('category', '')
            if not category:
                errors.append(f"{custom_file.name}: No category found")
                continue

            family = CATEGORY_TO_FAMILY.get(category)
            if not family:
                errors.append(f"{custom_file.name}: Unknown category '{category}'")
                continue

            sections = extract_sections(body)
            control_id = frontmatter.get('id', custom_file.stem.upper())

            new_content, slug = create_control_file(frontmatter, sections, family, control_id)

            # Create family directory if it doesn't exist
            family_dir = controls_dir / family
            family_dir.mkdir(parents=True, exist_ok=True)

            # Write new control file
            output_file = family_dir / f"{slug}.md"
            output_file.write_text(new_content)

            migrated.append({
                'source': custom_file.name,
                'dest': str(output_file.relative_to(controls_dir.parent)),
                'id': f"{family}-{slug}",
                'title': frontmatter.get('title', '')
            })

            print(f"  ✓ Migrated to {output_file.relative_to(controls_dir.parent)}")

        except Exception as e:
            errors.append(f"{custom_file.name}: {str(e)}")
            print(f"  ✗ Error: {e}")

    # Print summary
    print(f"\n{'='*60}")
    print("MIGRATION SUMMARY")
    print(f"{'='*60}")
    print(f"Migrated: {len(migrated)} controls")
    print(f"Errors: {len(errors)}")

    if migrated:
        print(f"\n{'='*60}")
        print("MIGRATED CONTROLS")
        print(f"{'='*60}")
        for item in migrated:
            print(f"{item['source']} → {item['dest']}")
            print(f"  ID: {item['id']}")
            print(f"  Title: {item['title']}")
            print()

    if errors:
        print(f"\n{'='*60}")
        print("ERRORS")
        print(f"{'='*60}")
        for error in errors:
            print(f"  ✗ {error}")

if __name__ == '__main__':
    migrate_custom_controls()
