package internal

// Markdown heading constants for consistent documentation generation
// These constants ensure uniform terminology and hierarchy across all framework generators

// Heading text constants
const (
	// HeadingFrameworkMappings is used for sections showing mappings to other frameworks
	// Used in: SCF, SOC2, GDPR, ISO 27001/27002, NIST 800-53
	HeadingFrameworkMappings = "Framework Mappings"

	// HeadingControlQuestions is used for SCF control questions section
	// Used in: SCF
	HeadingControlQuestions = "Control Questions"

	// HeadingGuidance is used for control guidance sections
	// Used in: NIST 800-53
	HeadingGuidance = "Guidance"

	// HeadingReferencedBy is used by backlinks tool (external)
	// Note: This is generated by separate tooling, not by these generators
	HeadingReferencedBy = "Referenced By"
)

// Heading level guidelines:
// - H1: Document title (framework + control ID)
// - H2: Major sections (Framework Mappings, Control Questions, Guidance)
// - H3: Subsections within major sections (individual framework names under Framework Mappings)
