#!/bin/bash

# Generate all 56 control documents for v2 structure

BASE="/Users/alexsmolen/src/github.com/engseclabs/graphgrc/docs-v2/controls"

# Function to create a control file
create_control() {
    local family=$1
    local filename=$2
    local title=$3
    local owner=${4:-"security-team"}

    cat > "$BASE/$family/$filename" << EOF
---
type: control
family: $family
title: $title
owner: $owner
last_reviewed: 2025-01-14
review_cadence: quarterly
---

# $title

Control for $title.

## Objective

[Control objective]

## Implementation

[How this control is implemented]

## Evidence

[Audit evidence for this control]

---

## Framework Mapping

<!-- Links to framework controls (SOC 2, GDPR, etc.) -->

---

## Referenced By

*This section is automatically generated by \`make generate-backlinks\`. Do not edit manually.*
EOF
}

# Asset Management (3)
create_control "asset-management" "saas-inventory.md" "SaaS Inventory"
create_control "asset-management" "cloud-inventory.md" "Cloud Inventory"
create_control "asset-management" "endpoint-inventory.md" "Endpoint Inventory"

# Monitoring (3)
create_control "monitoring" "infrastructure-observability.md" "Infrastructure Observability"
create_control "monitoring" "endpoint-observability.md" "Endpoint Observability"
create_control "monitoring" "siem.md" "Security Information and Events Management"

# Data Privacy (2)
create_control "data-privacy" "customer-personal-data.md" "Customer Personal Data"
create_control "data-privacy" "employee-personal-data.md" "Employee Personal Data"

# Cryptography (4)
create_control "cryptography" "code-signing.md" "Code Signing"
create_control "cryptography" "encryption-at-rest.md" "Encryption at Rest"
create_control "cryptography" "encryption-in-transit.md" "Encryption in Transit"
create_control "cryptography" "key-management.md" "Key Management"

# IAM (6)
create_control "iam" "saas-iam.md" "SaaS IAM"
create_control "iam" "password-management.md" "Password Management"
create_control "iam" "secrets-management.md" "Secrets Management"
create_control "iam" "single-sign-on.md" "Single Sign-On"
create_control "iam" "cloud-iam.md" "Cloud IAM"
create_control "iam" "multi-factor-authentication.md" "Multi-Factor Authentication"

# Vulnerability Management (3)
create_control "vulnerability-management" "cloud-vulnerability-detection.md" "Cloud Vulnerability Detection"
create_control "vulnerability-management" "endpoint-vulnerability-detection.md" "Endpoint Vulnerability Detection"
create_control "vulnerability-management" "vulnerability-management-process.md" "Vulnerability Management Process"

# Availability (3)
create_control "availability" "disaster-recovery.md" "Disaster Recovery"
create_control "availability" "availability-monitoring.md" "Availability Monitoring"
create_control "availability" "capacity-planning.md" "Capacity Planning"

# Personnel Security (3)
create_control "personnel-security" "insider-threat-mitigation.md" "Insider Threat Mitigation"
create_control "personnel-security" "personnel-lifecycle-management.md" "Personnel Lifecycle Management"
create_control "personnel-security" "rules-of-behavior.md" "Rules of Behavior"

# Threat Detection (3)
create_control "threat-detection" "endpoint-threat-detection.md" "Endpoint Threat Detection"
create_control "threat-detection" "saas-threat-detection.md" "SaaS Threat Detection"
create_control "threat-detection" "cloud-threat-detection.md" "Cloud Threat Detection"

# Compliance (5)
create_control "compliance" "contract-management.md" "Contract Management"
create_control "compliance" "internal-audits.md" "Internal Audits"
create_control "compliance" "grc-function.md" "GRC Function"
create_control "compliance" "external-audits.md" "External Audits"
create_control "compliance" "documentation-review.md" "Documentation Review"

# Security Assurance (4)
create_control "security-assurance" "security-reviews.md" "Security Reviews"
create_control "security-assurance" "penetration-tests.md" "Penetration Tests"
create_control "security-assurance" "bug-bounty-program.md" "Bug Bounty Program"
create_control "security-assurance" "customer-security-communications.md" "Customer Security Communications"

# Data Management (4)
create_control "data-management" "cloud-data-inventory.md" "Cloud Data Inventory"
create_control "data-management" "saas-data-inventory.md" "SaaS Data Inventory"
create_control "data-management" "data-classification.md" "Data Classification"
create_control "data-management" "data-retention-and-deletion.md" "Data Retention and Deletion"

# Configuration Management (3)
create_control "configuration-management" "saas-hardening.md" "SaaS Hardening"
create_control "configuration-management" "endpoint-hardening.md" "Endpoint Hardening"
create_control "configuration-management" "cloud-hardening.md" "Cloud Hardening"

# Incident Response (3)
create_control "incident-response" "security-incident-response.md" "Security Incident Response"
create_control "incident-response" "data-breach-response.md" "Data Breach Response"
create_control "incident-response" "incident-response-exercises.md" "Incident Response Exercises"

# Risk Management (2)
create_control "risk-management" "vendor-risk-management.md" "Vendor Risk Management"
create_control "risk-management" "organizational-risk-assessment.md" "Organizational Risk Assessment"

# Security Training (3)
create_control "security-training" "secure-coding-training.md" "Secure Coding Training"
create_control "security-training" "security-awareness-training.md" "Security Awareness Training"
create_control "security-training" "incident-response-training.md" "Incident Response Training"

# Physical Protection (1)
create_control "physical-protection" "office-security.md" "Office Security"

# Network Security (2)
create_control "network-security" "endpoint-network-security.md" "Endpoint Network Security"
create_control "network-security" "cloud-network-security.md" "Cloud Network Security"

# Security Engineering (3)
create_control "security-engineering" "automated-code-analysis.md" "Automated Code Analysis"
create_control "security-engineering" "secure-code-review.md" "Secure Code Review"
create_control "security-engineering" "secure-coding-standards.md" "Secure Coding Standards"

echo "Created all 56 controls!"
echo "Total files created:"
find "$BASE" -name "*.md" | wc -l
